import { SurveyEntry } from '../../model/surveyEntry'
import { Survey } from './../../model/survey'

export default class SurveyMapper {

    static map(firebaseObject: FirebaseSurvey, firebaseNodeId: string): Survey {
        // User entered wrong Id.
        if (firebaseObject == null) {
            const dummySurvey = new Survey()
            dummySurvey.name = 'Ungültige UmfrageId eingegeben'
            dummySurvey.surveyEntries.push(new SurveyEntry())
            return dummySurvey
        }
        // Overwrite Id as it is generated by firebase and we just placed a dummy value.
        firebaseObject.id = firebaseNodeId
        // Firebase converts arrays to key value pairs. https://stackoverflow.com/a/44264669/8524651
        firebaseObject.surveyEntries = Object.values(firebaseObject.surveyEntries)
        return new Survey(firebaseObject as Survey)
    }
}

export interface FirebaseSurvey {
    id: string
    name: string
    createdAt: number
    participations: number
    canSkip: boolean
    canSeeResult: boolean
    deadline: number
    isClosed: boolean
    surveyEntries: {[index: number]: SurveyEntry}
}